[uWSGI] getting INI configuration from wsgi.ini
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Jul 17 20:36:03 2018] ***
compiled with version: 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2) on 15 July 2018 20:53:39
os: Darwin-17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
nodename: Folarins-MacBook-Pro.local
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /Users/mrfobilli/IdeaProjects/AmazonReviews
detected binary path: /Users/mrfobilli/IdeaProjects/AmazonReviews/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 1418
your memory page size is 4096 bytes
detected max file descriptor number: 10240
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8080 fd 3
uwsgi socket 0 bound to UNIX address wsgi.sock fd 6
Python version: 3.6.4 (default, Jan  6 2018, 11:51:59)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7fa2e7800000
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145776 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fa2e7800000 pid: 39348 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 39348)
spawned uWSGI worker 1 (pid: 39385, cores: 1)
spawned uWSGI http 1 (pid: 39386)
[pid: 39385|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:36:07 2018] GET / => generated 3846 bytes in 25 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 775 bytes} [Tue Jul 17 20:36:07 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 7 msecs (HTTP/1.1 304) 5 headers in 202 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 3/3] 127.0.0.1 () {40 vars in 731 bytes} [Tue Jul 17 20:36:07 2018] GET /static/app.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 206 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 4/4] 127.0.0.1 () {40 vars in 737 bytes} [Tue Jul 17 20:36:07 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 5/5] 127.0.0.1 () {40 vars in 769 bytes} [Tue Jul 17 20:36:07 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 6/6] 127.0.0.1 () {40 vars in 746 bytes} [Tue Jul 17 20:36:07 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 7/7] 127.0.0.1 () {40 vars in 762 bytes} [Tue Jul 17 20:36:07 2018] GET /static/images/logo.png => generated 0 bytes in 3 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 8/8] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:36:33 2018] GET / => generated 3846 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 9/9] 127.0.0.1 () {40 vars in 775 bytes} [Tue Jul 17 20:36:33 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 202 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 10/10] 127.0.0.1 () {40 vars in 731 bytes} [Tue Jul 17 20:36:33 2018] GET /static/app.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 206 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 11/11] 127.0.0.1 () {40 vars in 762 bytes} [Tue Jul 17 20:36:33 2018] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 12/12] 127.0.0.1 () {40 vars in 737 bytes} [Tue Jul 17 20:36:33 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 13/13] 127.0.0.1 () {40 vars in 769 bytes} [Tue Jul 17 20:36:33 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 14/14] 127.0.0.1 () {40 vars in 746 bytes} [Tue Jul 17 20:36:33 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 15/15] 127.0.0.1 () {38 vars in 684 bytes} [Tue Jul 17 20:37:01 2018] GET / => generated 3834 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 81 bytes (2 switches on core 0)
[pid: 39385|app: 0|req: 16/16] 127.0.0.1 () {40 vars in 774 bytes} [Tue Jul 17 20:37:01 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 202 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 17/17] 127.0.0.1 () {40 vars in 730 bytes} [Tue Jul 17 20:37:01 2018] GET /static/app.css => generated 4061 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 8 headers in 303 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 18/18] 127.0.0.1 () {40 vars in 761 bytes} [Tue Jul 17 20:37:01 2018] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 19/19] 127.0.0.1 () {40 vars in 736 bytes} [Tue Jul 17 20:37:01 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 20/20] 127.0.0.1 () {40 vars in 768 bytes} [Tue Jul 17 20:37:01 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 21/21] 127.0.0.1 () {40 vars in 745 bytes} [Tue Jul 17 20:37:01 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 22/22] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:37:51 2018] GET / => generated 3843 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 23/23] 127.0.0.1 () {40 vars in 775 bytes} [Tue Jul 17 20:37:51 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 202 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 24/24] 127.0.0.1 () {40 vars in 731 bytes} [Tue Jul 17 20:37:51 2018] GET /static/app.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 206 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 25/25] 127.0.0.1 () {40 vars in 762 bytes} [Tue Jul 17 20:37:51 2018] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 26/26] 127.0.0.1 () {40 vars in 737 bytes} [Tue Jul 17 20:37:51 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 27/27] 127.0.0.1 () {40 vars in 769 bytes} [Tue Jul 17 20:37:51 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 28/28] 127.0.0.1 () {40 vars in 746 bytes} [Tue Jul 17 20:37:51 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 29/29] 127.0.0.1 () {38 vars in 661 bytes} [Tue Jul 17 20:38:02 2018] GET /search?q=I%20&auto=false => generated 233 bytes in 12 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 30/30] 127.0.0.1 () {38 vars in 661 bytes} [Tue Jul 17 20:38:04 2018] GET /search?q=I%20&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 31/31] 127.0.0.1 () {38 vars in 663 bytes} [Tue Jul 17 20:38:04 2018] GET /search?q=I%20w&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 32/32] 127.0.0.1 () {38 vars in 665 bytes} [Tue Jul 17 20:38:04 2018] GET /search?q=I%20wo&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 33/33] 127.0.0.1 () {38 vars in 667 bytes} [Tue Jul 17 20:38:04 2018] GET /search?q=I%20wor&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 34/34] 127.0.0.1 () {38 vars in 665 bytes} [Tue Jul 17 20:38:05 2018] GET /search?q=I%20wo&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (2 switches on core 0)
[pid: 39385|app: 0|req: 35/35] 127.0.0.1 () {38 vars in 663 bytes} [Tue Jul 17 20:38:05 2018] GET /search?q=I%20w&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 36/36] 127.0.0.1 () {38 vars in 661 bytes} [Tue Jul 17 20:38:05 2018] GET /search?q=I%20&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 37/37] 127.0.0.1 () {38 vars in 663 bytes} [Tue Jul 17 20:38:05 2018] GET /search?q=I%20a&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 38/38] 127.0.0.1 () {38 vars in 665 bytes} [Tue Jul 17 20:38:05 2018] GET /search?q=I%20am&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 39/39] 127.0.0.1 () {38 vars in 671 bytes} [Tue Jul 17 20:38:05 2018] GET /search?q=I%20am%20&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 40/40] 127.0.0.1 () {38 vars in 673 bytes} [Tue Jul 17 20:38:05 2018] GET /search?q=I%20am%20w&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 41/41] 127.0.0.1 () {38 vars in 675 bytes} [Tue Jul 17 20:38:06 2018] GET /search?q=I%20am%20wo&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 42/42] 127.0.0.1 () {38 vars in 677 bytes} [Tue Jul 17 20:38:06 2018] GET /search?q=I%20am%20wor&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 43/43] 127.0.0.1 () {38 vars in 679 bytes} [Tue Jul 17 20:38:06 2018] GET /search?q=I%20am%20worr&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 44/44] 127.0.0.1 () {38 vars in 681 bytes} [Tue Jul 17 20:38:06 2018] GET /search?q=I%20am%20worri&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 45/45] 127.0.0.1 () {38 vars in 683 bytes} [Tue Jul 17 20:38:06 2018] GET /search?q=I%20am%20worrie&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 46/46] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:38:06 2018] GET /search?q=I%20am%20worried&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 47/47] 127.0.0.1 () {38 vars in 721 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 48/48] 127.0.0.1 () {38 vars in 714 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 49/49] 127.0.0.1 () {38 vars in 714 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 50/50] 127.0.0.1 () {38 vars in 714 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 51/51] 127.0.0.1 () {38 vars in 714 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 52/52] 127.0.0.1 () {38 vars in 714 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 53/53] 127.0.0.1 () {38 vars in 714 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 5 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 54/54] 127.0.0.1 () {38 vars in 714 bytes} [Tue Jul 17 20:38:08 2018] GET /?q=I+am+worried => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 55/55] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:38:18 2018] GET / => generated 3843 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 56/56] 127.0.0.1 () {40 vars in 775 bytes} [Tue Jul 17 20:38:18 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 202 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 57/57] 127.0.0.1 () {40 vars in 731 bytes} [Tue Jul 17 20:38:18 2018] GET /static/app.css => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 206 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 58/58] 127.0.0.1 () {40 vars in 762 bytes} [Tue Jul 17 20:38:18 2018] GET /static/images/logo.png => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 59/59] 127.0.0.1 () {40 vars in 737 bytes} [Tue Jul 17 20:38:18 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 60/60] 127.0.0.1 () {40 vars in 769 bytes} [Tue Jul 17 20:38:18 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 61/61] 127.0.0.1 () {40 vars in 746 bytes} [Tue Jul 17 20:38:18 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 62/62] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:38:19 2018] GET / => generated 3843 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 63/63] 127.0.0.1 () {40 vars in 775 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 202 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 64/64] 127.0.0.1 () {40 vars in 731 bytes} [Tue Jul 17 20:38:19 2018] GET /static/app.css => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 206 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 65/65] 127.0.0.1 () {40 vars in 762 bytes} [Tue Jul 17 20:38:19 2018] GET /static/images/logo.png => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 66/66] 127.0.0.1 () {40 vars in 737 bytes} [Tue Jul 17 20:38:19 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 67/67] 127.0.0.1 () {40 vars in 769 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 68/68] 127.0.0.1 () {40 vars in 746 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 69/69] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:38:19 2018] GET / => generated 3843 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 70/70] 127.0.0.1 () {40 vars in 775 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 202 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 71/71] 127.0.0.1 () {40 vars in 731 bytes} [Tue Jul 17 20:38:19 2018] GET /static/app.css => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 206 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 72/72] 127.0.0.1 () {40 vars in 762 bytes} [Tue Jul 17 20:38:19 2018] GET /static/images/logo.png => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 73/73] 127.0.0.1 () {40 vars in 737 bytes} [Tue Jul 17 20:38:19 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 74/74] 127.0.0.1 () {40 vars in 769 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 75/75] 127.0.0.1 () {40 vars in 746 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 76/76] 127.0.0.1 () {38 vars in 685 bytes} [Tue Jul 17 20:38:19 2018] GET / => generated 3843 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 77/77] 127.0.0.1 () {40 vars in 775 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/css/bootstrap.min.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 202 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 78/78] 127.0.0.1 () {40 vars in 731 bytes} [Tue Jul 17 20:38:19 2018] GET /static/app.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 5 headers in 206 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 79/79] 127.0.0.1 () {40 vars in 762 bytes} [Tue Jul 17 20:38:19 2018] GET /static/images/logo.png => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 80/80] 127.0.0.1 () {40 vars in 737 bytes} [Tue Jul 17 20:38:19 2018] GET /static/jquery/jquery.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 81/81] 127.0.0.1 () {40 vars in 769 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/js/bootstrap.bundle.min.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 201 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 82/82] 127.0.0.1 () {40 vars in 746 bytes} [Tue Jul 17 20:38:19 2018] GET /static/bootstrap/js/typeahead.js => generated 0 bytes in 0 msecs (HTTP/1.1 304) 5 headers in 200 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 83/83] 127.0.0.1 () {38 vars in 697 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 84/84] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 85/85] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 86/86] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 87/87] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 88/88] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 89/89] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 5 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 90/90] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 17 20:38:20 2018] GET /?q= => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 39385|app: 0|req: 91/91] 127.0.0.1 () {38 vars in 657 bytes} [Tue Jul 17 20:38:40 2018] GET /search?q=qw&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 92/92] 127.0.0.1 () {38 vars in 659 bytes} [Tue Jul 17 20:38:40 2018] GET /search?q=qwe&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 39385|app: 0|req: 93/93] 127.0.0.1 () {38 vars in 661 bytes} [Tue Jul 17 20:38:40 2018] GET /search?q=qwew&auto=false => generated 233 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 94/94] 127.0.0.1 () {38 vars in 705 bytes} [Tue Jul 17 20:38:41 2018] GET /?q=qwew => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 95/95] 127.0.0.1 () {38 vars in 698 bytes} [Tue Jul 17 20:38:41 2018] GET /?q=qwew => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 96/96] 127.0.0.1 () {38 vars in 698 bytes} [Tue Jul 17 20:38:41 2018] GET /?q=qwew => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 97/97] 127.0.0.1 () {38 vars in 698 bytes} [Tue Jul 17 20:38:41 2018] GET /?q=qwew => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 98/98] 127.0.0.1 () {38 vars in 698 bytes} [Tue Jul 17 20:38:41 2018] GET /?q=qwew => generated 0 bytes in 5 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 99/99] 127.0.0.1 () {38 vars in 698 bytes} [Tue Jul 17 20:38:41 2018] GET /?q=qwew => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/web.py", line 33, in home
    image = classifier.predict(q)[0].split('.')[0] + '.png'
  File "./classify_ratings_bayes.py", line 77, in predict
    model()
  File "./classify_ratings_bayes.py", line 40, in model
    with open(DATA_FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../train_data.txt'
[pid: 39385|app: 0|req: 100/100] 127.0.0.1 () {38 vars in 698 bytes} [Tue Jul 17 20:38:41 2018] GET /?q=qwew => generated 0 bytes in 5 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 39386)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1943, in shutdown
    h.flush()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 975, in flush
    if self.stream and hasattr(self.stream, "flush"):
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/werkzeug/local.py", line 328, in __bool__
    return bool(self._get_current_object())
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/mrfobilli/IdeaProjects/AmazonReviews/venv/lib/python3.6/site-packages/flask/logging.py", line 30, in wsgi_errors_stream
    return request.environ['wsgi.errors'] if request else sys.stderr
KeyError: 'wsgi.errors'
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket wsgi.sock removed.
